#url: http://iseetheline.ru
url: http://localhost:4000
markdown: rdiscount
pygments: true
permalink: /:title
future: false
paginate: 7

rdiscount:
  extensions: [smart]

title: Блог Павла Попова
author: Павел Попов
years: 2011&mdash;2013
twitter: schmooser
edit_url: https://github.com/schmooser/schmooser.github.io/blob/master/ 
