
markdown: kramdown
highlighter: true
permalink: :title/
future: false
paginate: 7

rdiscount:
  extensions: [smart]

title: Блог Павла Попова
tagline: Блог
description: 'Переводы научно-популярных статей, английский язык, путешествия, программирование, СУБД.'
#url: http://iseetheline.ru

baseurl: ""

author:
    name: Павел Попов
    twitter: schmooser
    email: schmooser@gmail.com

paginate: 7
excerpt_separator: <!--more-->

edit_url: https://github.com/schmooser/schmooser.github.io/blob/master/
feedburner_url: http://feeds.feedburner.com/pavelpopov/rss

disqus:
    #shortname: iseetheline
    url: http://iseetheline.ru

flickr:
    key: f162f2bd093e4b60d2167158a4d67513
    user_id: 21960065@N03

