#url: http://iseetheline.ru
markdown: rdiscount
pygments: true
permalink: /:title
future: false
#paginate: 7

rdiscount:
  extensions: [smart]

title: Блог Павла Попова
author: Павел Попов
years: 2011&mdash;2013
